export enum RespTypeList {
    SUCCESS = 1,
    GENERIC_ERROR,
    DATA_INVALID,

    // RoomManager
    ROOM_ID_EMPTY,
    ROOM_NOT_EXIST,
    ROOM_PASSWORD_WRONG,
    ROOM_HAS_BEEN_BEFORE,
    ROOM_NOT_BEEN_IN,

    // VarManager
    VAR_NO_WRITE_PERMISSION,
    VAR_KEY_NOT_FOUND,
    VAR_VALUE_NOT_CHANGE,
    VAR_NO_READ_PERMISSION,
    VAR_NO_UPDATE_PERMISSION,
    VAR_NO_DELETE_PERMISSION,
    VAR_NO_ENTRY,
}